from distutils.core import setup

setup(
    name='pythontests',
    version='0.0.1',
    packages=['venv3.Lib.distutils', 'venv3.Lib.encodings', 'venv3.Lib.importlib', 'venv3.Lib.collections',
              'venv3.Lib.site-packages.pip', 'venv3.Lib.site-packages.pip.req', 'venv3.Lib.site-packages.pip.vcs',
              'venv3.Lib.site-packages.pip.utils', 'venv3.Lib.site-packages.pip.compat',
              'venv3.Lib.site-packages.pip.models', 'venv3.Lib.site-packages.pip._vendor',
              'venv3.Lib.site-packages.pip._vendor.distlib', 'venv3.Lib.site-packages.pip._vendor.distlib._backport',
              'venv3.Lib.site-packages.pip._vendor.colorama', 'venv3.Lib.site-packages.pip._vendor.html5lib',
              'venv3.Lib.site-packages.pip._vendor.html5lib.trie',
              'venv3.Lib.site-packages.pip._vendor.html5lib.filters',
              'venv3.Lib.site-packages.pip._vendor.html5lib.serializer',
              'venv3.Lib.site-packages.pip._vendor.html5lib.treewalkers',
              'venv3.Lib.site-packages.pip._vendor.html5lib.treeadapters',
              'venv3.Lib.site-packages.pip._vendor.html5lib.treebuilders',
              'venv3.Lib.site-packages.pip._vendor.lockfile', 'venv3.Lib.site-packages.pip._vendor.progress',
              'venv3.Lib.site-packages.pip._vendor.requests', 'venv3.Lib.site-packages.pip._vendor.requests.packages',
              'venv3.Lib.site-packages.pip._vendor.requests.packages.chardet',
              'venv3.Lib.site-packages.pip._vendor.requests.packages.urllib3',
              'venv3.Lib.site-packages.pip._vendor.requests.packages.urllib3.util',
              'venv3.Lib.site-packages.pip._vendor.requests.packages.urllib3.contrib',
              'venv3.Lib.site-packages.pip._vendor.requests.packages.urllib3.packages',
              'venv3.Lib.site-packages.pip._vendor.requests.packages.urllib3.packages.ssl_match_hostname',
              'venv3.Lib.site-packages.pip._vendor.packaging', 'venv3.Lib.site-packages.pip._vendor._markerlib',
              'venv3.Lib.site-packages.pip._vendor.cachecontrol',
              'venv3.Lib.site-packages.pip._vendor.cachecontrol.caches',
              'venv3.Lib.site-packages.pip._vendor.pkg_resources',
              'venv3.Lib.site-packages.pip._vendor.pkg_resources.tests', 'venv3.Lib.site-packages.pip.commands',
              'venv3.Lib.site-packages.pip.operations', 'venv3.Lib.site-packages._markerlib',
              'venv3.Lib.site-packages.setuptools', 'venv3.Lib.site-packages.setuptools.tests',
              'venv3.Lib.site-packages.setuptools.command', 'venv3.Lib.site-packages.pkg_resources',
              'venv3.Lib.site-packages.pkg_resources.tests', 'venv3.Lib.site-packages.pkg_resources._vendor',
              'venv3.Lib.site-packages.pkg_resources._vendor.packaging'],
    url='',
    license='MIT',
    author='asjoberg',
    author_email='shoobah@gmail.com',
    description='testar python'
)
